//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTWEB_110HN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVHOPTAC
    {
        public int idDVHT { get; set; }
        public string tenDVHT { get; set; }
        public string motaDVHT { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
    }
}
